# -*- coding: utf-8 -*-
"""calculator twice repeat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dPIq7Sr01u22-bzrdnu_KTWDSykwvk_-
"""

from art3 import logo
print(logo)

#operations in calculator
def addition(n1,n2):
  return(n1+n2)

def subtract(n1,n2):
  return (n1-n1)

def multiply(n1,n2):
  return (n1*n1)

def divide(n1,n2):
  return (n1/n2)

def power(n1,n2):
  return (n1**n2)

def remainder(n1,n2):
  return n1%n2

cal={'+': addition, '-':subtract, '*':multiply, '/':divide, '**':power, '%':remainder}

a1 = int(input("Enter first number"))
b1 = int(input("Enter the second number"))
for i in cal:
  print(i)
choice1 = input("choose one of the above operations")
function1 = cal[choice1]
answer1 = function1(a1,b1)
print(f"{a1} {choice1} {b1} = {answer1}")

choice2 = input("Again choose one of the above operations")
function2 = cal[choice2]
c1 = int(input("Enter another number"))
answer2 = function2(answer1, c1)
print(f"{answer1} {choice2} {c1} = {answer2}")